### ISSUE TITLE
Implement second task

### ISSUE THREAD

**Issue by ojles** [ojles/teamnull#2]
* figure out about [SotredList](https://docs.microsoft.com/en-us/dotnet/api/system.collections.sortedlist?view=netframework-4.7.2)
* define perimeter() method in ColoredTriangle
* read triangles from file into SortedList and sort them by perimeter

> Зчитати дані в колекцію SortedList кольорових трикутників. Фігури повинні бути посортовані за периметрами. Вивести результат у файл1

**Comment by mranch** [comment]
hello
